development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: gigitt_development
  pool: 5
  username: justindoshay
  password: N0m@rebs

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: gigitt_test
  pool: 5
  username: justindoshay
  password: N0m@rebs

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: d47ch3h4v99h74
  pool: 5
  username: u5jpr90em6sb2t
  password: p3rumh1ro168dcad26caemeeot5
